var video = document.getElementById('videoElement');
var scale = 2;
var canvas = document.createElement("canvas");
canvas.width = video.videoWidth * scale;
canvas.height = video.videoHeight * scale;
canvas.getContext('2d').drawImage(video, 0, 0, canvas.width, canvas.height);
// canvas.getContext('2d').drawImage(video, 0, 0, 640, 480);


imgCam.setSrc(canvas.toDataURL());

// diaImage.close();

tabs.setSelectedKey('capture');
